name: Deploy Prod Ilhabela Wake

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Get latest code
      uses: actions/checkout@v2
    
    - name: Sync files
      uses: easingthemes/ssh-deploy@v2.1.5
      env:
        ARGS: >-  
            -rltgoDzvO
            --exclude='.git'
        TARGET: ${{ secrets.REMOTE_TARGET }}
        SSH_PRIVATE_KEY: ${{ secrets.RSA_PRIVATE_KEY }}
        REMOTE_HOST: ${{ secrets.SERVER_HOST }}
        REMOTE_USER: ${{ secrets.REMOTE_USER }}
        REMOTE_PORT: ${{ secrets.REMOTE_PORT }}